name       : cppzmq
version    : 4.2.1
release    : 1
source     :
    - https://github.com/zeromq/cppzmq/archive/v4.2.1.tar.gz : 11c699001659336c7d46779f714f3e9d15d63343cd2ae7c1905e4bf58907cef9
license    : MIT
component  : programming
summary    : C++ binding for 0MQ
description: |
    C++ binding for 0MQ
patterns   :
    - /usr/include/*
install    : |
    install -Dm00644 $workdir/zmq.hpp $installdir/usr/include/zmq.hpp
    install -Dm00644 $workdir/zmq_addon.hpp $installdir/usr/include/zmq_addon.hpp
