name       : cppzmq
version    : 4.3.0
release    : 3
source     :
    - https://github.com/zeromq/cppzmq/archive/v4.3.0.tar.gz : 27d1f56406ba94ee779e639203218820975cf68174f92fbeae0f645df0fcada4
license    : MIT
component  : programming
summary    : C++ binding for 0MQ/ZMQ/ZeroMQ
description: |
    C++ binding for 0MQ/ZMQ/ZeroMQ
patterns   :
    - /usr/include/*
builddeps  :
    - pkgconfig(libzmq)
setup      : |
    # Why is it so hard?
    sed -i '23,25d' CMakeLists.txt

    %cmake -DCPPZMQ_BUILD_TESTS=OFF
build      : |
    %make
install    : |
    %make_install
