name       : cppzmq
version    : 4.2.3
release    : 2
source     :
    - https://github.com/zeromq/cppzmq/archive/v4.2.3.tar.gz : 3e6b57bf49115f4ae893b1ff7848ead7267013087dc7be1ab27636a97144d373
license    : MIT
component  : programming
summary    : C++ binding for 0MQ/ZMQ/ZeroMQ
description: |
    C++ binding for 0MQ/ZMQ/ZeroMQ
patterns   :
    - /usr/include/*
builddeps  :
    - pkgconfig(libzmq)
setup      : |
    %cmake .
build      : |
    %make
install    : |
    %make_install
