name       : cppzmq
version    : 4.8.1
release    : 4
source     :
    - https://github.com/zeromq/cppzmq/archive/v4.8.1.tar.gz : 7a23639a45f3a0049e11a188e29aaedd10b2f4845f0000cf3e22d6774ebde0af
license    : MIT
component  : programming
summary    : C++ binding for 0MQ/ZMQ/ZeroMQ
description: |
    C++ binding for 0MQ/ZMQ/ZeroMQ
patterns   :
    - /*
builddeps  :
    - pkgconfig(libzmq)
setup      : |
    %cmake -DCPPZMQ_BUILD_TESTS=OFF
build      : |
    %make
install    : |
    %make_install
check      : |
    # This will fail if this version of cppzmq is incompatible with the version of zeromq
    gcc -c zmq.hpp -o ./test.o
